stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/train.dat
    outs:
    - data/raw/train.csv

  preprocessed_data:
    cmd: python src/data_preprocessing.py --config=params.yaml
    deps:
    - src/data_preprocessing.py
    - data/raw/train.csv
    outs:
    - data/processed/processed_Train.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/processed/processed_Train.csv
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_data.csv
    - data/processed/test_data.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.AdaBoostClassifier.params.n_estimators
    - estimators.AdaBoostClassifier.params.learning_rate
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib